# Use root/example as user/password credentials
version: '3.1'

services:
  anzu:
    build: .
    ports:
      - 3200:3200
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/
      MONGO_NAME: anzu
      AWS_ACCESS_KEY_ID: minio
      AWS_SECRET_ACCESS_KEY: minio123
      AWS_S3_ENDPOINT: http://minio:9000
    depends_on:
      - mongo
      - minio
  mongo:
    image: mongo:3
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
  minio:
    image: minio/minio
    restart: always
    ports:
      - 9000:9000
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data
volumes:
  minio-data: